@baseUrl = http://localhost:5216
@idGet = eb59f207-10f2-405d-8e7d-e8ea651c653e
@idDelete = eb59f207-10f2-405d-8e7d-e8ea651c653e

###
GET {{baseUrl}}/api/newsletters
Accept: application/json

###
GET {{baseUrl}}/api/newsletters/{{idGet}}
Accept: application/json

###
POST {{baseUrl}}/api/newsletters
Content-Type: application/json

{
  "id": "{{$guid}}",
  "title": "Nova notícia de teste",
  "content": "Conteúdo da notícia gerado manualmente"
}

###
PUT {{baseUrl}}/api/newsletters
Content-Type: application/json

{
  "id": "cc90e334-0321-40a0-878c-6b40fc72ab67",
  "title": "Título atualizado",
  "subTitle": "",
  "content": ""
}

###
DELETE {{baseUrl}}/api/newsletters/{{idDelete}}
Accept: application/json

###
GET {{baseUrl}}/raspar-noticias
